# jdk7
#
# VERSION       1.0

FROM ubuntu:12.04
MAINTAINER UberConverter <admin@uberconverter.com>

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get install -y python-software-properties
RUN add-apt-repository -y ppa:libreoffice/libreoffice-4-2
RUN apt-get update
RUN apt-get install -y libreoffice 
RUN apt-get install -y unoconv

