FROM jdk7
MAINTAINER UberConverter <admin@uberconverter.com>

RUN apt-get install -y wget

RUN wget http://mirror.ox.ac.uk/sites/rsync.apache.org/tika/tika-app-1.5.jar
RUN wget http://repo1.maven.org/maven2/org/apache/tika/tika-server/1.5/tika-server-1.5.jar

